---
title: "data_import"
output: github_document
date: "2025-09-16"
---

```{r setup}
library(tidyverse)
library(readxl)
```

## Read in some data

```{r}
litters_df <- read_csv("/Users/zhengchenhao/Desktop/2025Fall/DS/New_Data_Wrangling_I/data/FAS_litters.csv")
litters_df <-janitor::clean_names(litters_df)
```

## Take a look at the data
```{r}
litters_df
```

```{r}
head(litters_df)
```

```{r}
tail(litters_df)
```

```{r}
skimr::skim(litters_df)
```
## Option to read_csv
```{r}
litters_df<-read_csv("/Users/zhengchenhao/Desktop/2025Fall/DS/New_Data_Wrangling_I/data/FAS_litters.csv",skip=10,col_names = FALSE)
```

## Other file formats
```{r}
mlb_df<-read_excel("/Users/zhengchenhao/Desktop/2025Fall/DS/New_Data_Wrangling_I/data/mlb11.xlsx")
mlb_df
```

### Subset
```{r}
mlb_df<-read_excel("/Users/zhengchenhao/Desktop/2025Fall/DS/New_Data_Wrangling_I/data/mlb11.xlsx",range="A1:F7")
mlb_df
```

## Read in a SAS file
```{r}
library(haven)
pulse_df<-read_sas("/Users/zhengchenhao/Desktop/2025Fall/DS/New_Data_Wrangling_I/data/public_pulse_data.sas7bdat")
pulse_df
```

## Export data
```{r}
write_csv(mlb_df,"/Users/zhengchenhao/Desktop/2025Fall/DS/New_Data_Wrangling_I/mlb_subtable.csv")
```

